// Generated by gencpp from file joystick_command/Rel_error_joystick.msg
// DO NOT EDIT!


#ifndef JOYSTICK_COMMAND_MESSAGE_REL_ERROR_JOYSTICK_H
#define JOYSTICK_COMMAND_MESSAGE_REL_ERROR_JOYSTICK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace joystick_command
{
template <class ContainerAllocator>
struct Rel_error_joystick_
{
  typedef Rel_error_joystick_<ContainerAllocator> Type;

  Rel_error_joystick_()
    : header()
    , error_roll(0.0)
    , error_pitch(0.0)
    , error_yaw(0.0)
    , error_distance(0.0)
    , error_depth(0.0)
    , error_surge_speed(0.0)
    , error_sway_speed(0.0)  {
    }
  Rel_error_joystick_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , error_roll(0.0)
    , error_pitch(0.0)
    , error_yaw(0.0)
    , error_distance(0.0)
    , error_depth(0.0)
    , error_surge_speed(0.0)
    , error_sway_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _error_roll_type;
  _error_roll_type error_roll;

   typedef double _error_pitch_type;
  _error_pitch_type error_pitch;

   typedef double _error_yaw_type;
  _error_yaw_type error_yaw;

   typedef double _error_distance_type;
  _error_distance_type error_distance;

   typedef double _error_depth_type;
  _error_depth_type error_depth;

   typedef double _error_surge_speed_type;
  _error_surge_speed_type error_surge_speed;

   typedef double _error_sway_speed_type;
  _error_sway_speed_type error_sway_speed;





  typedef boost::shared_ptr< ::joystick_command::Rel_error_joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joystick_command::Rel_error_joystick_<ContainerAllocator> const> ConstPtr;

}; // struct Rel_error_joystick_

typedef ::joystick_command::Rel_error_joystick_<std::allocator<void> > Rel_error_joystick;

typedef boost::shared_ptr< ::joystick_command::Rel_error_joystick > Rel_error_joystickPtr;
typedef boost::shared_ptr< ::joystick_command::Rel_error_joystick const> Rel_error_joystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joystick_command::Rel_error_joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::joystick_command::Rel_error_joystick_<ContainerAllocator1> & lhs, const ::joystick_command::Rel_error_joystick_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.error_roll == rhs.error_roll &&
    lhs.error_pitch == rhs.error_pitch &&
    lhs.error_yaw == rhs.error_yaw &&
    lhs.error_distance == rhs.error_distance &&
    lhs.error_depth == rhs.error_depth &&
    lhs.error_surge_speed == rhs.error_surge_speed &&
    lhs.error_sway_speed == rhs.error_sway_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::joystick_command::Rel_error_joystick_<ContainerAllocator1> & lhs, const ::joystick_command::Rel_error_joystick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace joystick_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joystick_command::Rel_error_joystick_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joystick_command::Rel_error_joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joystick_command::Rel_error_joystick_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb21a06c4e8dda99b50b5307a898900c";
  }

  static const char* value(const ::joystick_command::Rel_error_joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb21a06c4e8dda99ULL;
  static const uint64_t static_value2 = 0xb50b5307a898900cULL;
};

template<class ContainerAllocator>
struct DataType< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joystick_command/Rel_error_joystick";
  }

  static const char* value(const ::joystick_command::Rel_error_joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 error_roll          # Roll relative error   [deg]\n"
"float64 error_pitch         # Pitch relative error  [deg]\n"
"float64 error_yaw           # Yaw relative error    [deg]\n"
"\n"
"float64 error_distance      # Frontal distance relative error   [m]\n"
"float64 error_depth         # Depth relative error              [m]\n"
"\n"
"float64 error_surge_speed   # Desired absolute surge speed (x axis) [m/s]\n"
"float64 error_sway_speed    # Desired absolute sway speed (y axis)  [m/s]\n"
"\n"
"#                #     SURGE SPEED    #     SWAY SPEED    #     YAW RATE     #    DEPTH RATE    #     PITCH RATE     #\n"
"# ------------------------------------------------------------------------------------------------------------------ #\n"
"#    MAX VALUES  #      0.25 m/s      #      0.25 m/s     #     10 deg/s     #    0.125 m/s     #      5.0 deg/s     #\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::joystick_command::Rel_error_joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.error_roll);
      stream.next(m.error_pitch);
      stream.next(m.error_yaw);
      stream.next(m.error_distance);
      stream.next(m.error_depth);
      stream.next(m.error_surge_speed);
      stream.next(m.error_sway_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rel_error_joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joystick_command::Rel_error_joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joystick_command::Rel_error_joystick_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "error_roll: ";
    Printer<double>::stream(s, indent + "  ", v.error_roll);
    s << indent << "error_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.error_pitch);
    s << indent << "error_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.error_yaw);
    s << indent << "error_distance: ";
    Printer<double>::stream(s, indent + "  ", v.error_distance);
    s << indent << "error_depth: ";
    Printer<double>::stream(s, indent + "  ", v.error_depth);
    s << indent << "error_surge_speed: ";
    Printer<double>::stream(s, indent + "  ", v.error_surge_speed);
    s << indent << "error_sway_speed: ";
    Printer<double>::stream(s, indent + "  ", v.error_sway_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOYSTICK_COMMAND_MESSAGE_REL_ERROR_JOYSTICK_H
