# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from marta_msgs/MotionReference.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import marta_msgs.msg
import std_msgs.msg

class MotionReference(genpy.Message):
  _md5sum = "f6865ee91600578e5e1d5b6edf162a80"
  _type = "marta_msgs/MotionReference"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

LatitudeLongitudeAltitude lla

LatitudeLongitudeDepth lld

Quaternion quaternion

RollPitchYaw rpy

RollPitchYaw rpy_dot

RollPitchYaw rpy_dot_dot

NorthEastDown pn_wrt_home

NorthEastDown pn_dot

NorthEastDown pn_dot_dot

SurgeSwayHeave vb

SurgeSwayHeave vb_dot

SurgeSwayHeave wb

SurgeSwayHeave wb_dot

float64 depth_unconstrained
	
bool final_reference

LatitudeLongitudeAltitude lla_final

RollPitchYaw rpy_final
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: marta_msgs/LatitudeLongitudeAltitude
float64 latitude
float64 longitude
float64 altitude

================================================================================
MSG: marta_msgs/LatitudeLongitudeDepth
float64 latitude
float64 longitude
float64 depth

================================================================================
MSG: marta_msgs/Quaternion
float64 w
float64 x
float64 y
float64 z

================================================================================
MSG: marta_msgs/RollPitchYaw
float64 roll
float64 pitch
float64 yaw

================================================================================
MSG: marta_msgs/NorthEastDown
float64 north
float64 east
float64 down

================================================================================
MSG: marta_msgs/SurgeSwayHeave
float64 surge
float64 sway
float64 heave
"""
  __slots__ = ['header','lla','lld','quaternion','rpy','rpy_dot','rpy_dot_dot','pn_wrt_home','pn_dot','pn_dot_dot','vb','vb_dot','wb','wb_dot','depth_unconstrained','final_reference','lla_final','rpy_final']
  _slot_types = ['std_msgs/Header','marta_msgs/LatitudeLongitudeAltitude','marta_msgs/LatitudeLongitudeDepth','marta_msgs/Quaternion','marta_msgs/RollPitchYaw','marta_msgs/RollPitchYaw','marta_msgs/RollPitchYaw','marta_msgs/NorthEastDown','marta_msgs/NorthEastDown','marta_msgs/NorthEastDown','marta_msgs/SurgeSwayHeave','marta_msgs/SurgeSwayHeave','marta_msgs/SurgeSwayHeave','marta_msgs/SurgeSwayHeave','float64','bool','marta_msgs/LatitudeLongitudeAltitude','marta_msgs/RollPitchYaw']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lla,lld,quaternion,rpy,rpy_dot,rpy_dot_dot,pn_wrt_home,pn_dot,pn_dot_dot,vb,vb_dot,wb,wb_dot,depth_unconstrained,final_reference,lla_final,rpy_final

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotionReference, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lla is None:
        self.lla = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.lld is None:
        self.lld = marta_msgs.msg.LatitudeLongitudeDepth()
      if self.quaternion is None:
        self.quaternion = marta_msgs.msg.Quaternion()
      if self.rpy is None:
        self.rpy = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot is None:
        self.rpy_dot = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot_dot is None:
        self.rpy_dot_dot = marta_msgs.msg.RollPitchYaw()
      if self.pn_wrt_home is None:
        self.pn_wrt_home = marta_msgs.msg.NorthEastDown()
      if self.pn_dot is None:
        self.pn_dot = marta_msgs.msg.NorthEastDown()
      if self.pn_dot_dot is None:
        self.pn_dot_dot = marta_msgs.msg.NorthEastDown()
      if self.vb is None:
        self.vb = marta_msgs.msg.SurgeSwayHeave()
      if self.vb_dot is None:
        self.vb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.wb is None:
        self.wb = marta_msgs.msg.SurgeSwayHeave()
      if self.wb_dot is None:
        self.wb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.depth_unconstrained is None:
        self.depth_unconstrained = 0.
      if self.final_reference is None:
        self.final_reference = False
      if self.lla_final is None:
        self.lla_final = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.rpy_final is None:
        self.rpy_final = marta_msgs.msg.RollPitchYaw()
    else:
      self.header = std_msgs.msg.Header()
      self.lla = marta_msgs.msg.LatitudeLongitudeAltitude()
      self.lld = marta_msgs.msg.LatitudeLongitudeDepth()
      self.quaternion = marta_msgs.msg.Quaternion()
      self.rpy = marta_msgs.msg.RollPitchYaw()
      self.rpy_dot = marta_msgs.msg.RollPitchYaw()
      self.rpy_dot_dot = marta_msgs.msg.RollPitchYaw()
      self.pn_wrt_home = marta_msgs.msg.NorthEastDown()
      self.pn_dot = marta_msgs.msg.NorthEastDown()
      self.pn_dot_dot = marta_msgs.msg.NorthEastDown()
      self.vb = marta_msgs.msg.SurgeSwayHeave()
      self.vb_dot = marta_msgs.msg.SurgeSwayHeave()
      self.wb = marta_msgs.msg.SurgeSwayHeave()
      self.wb_dot = marta_msgs.msg.SurgeSwayHeave()
      self.depth_unconstrained = 0.
      self.final_reference = False
      self.lla_final = marta_msgs.msg.LatitudeLongitudeAltitude()
      self.rpy_final = marta_msgs.msg.RollPitchYaw()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_41dB6d().pack(_x.lla.latitude, _x.lla.longitude, _x.lla.altitude, _x.lld.latitude, _x.lld.longitude, _x.lld.depth, _x.quaternion.w, _x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.rpy_dot.roll, _x.rpy_dot.pitch, _x.rpy_dot.yaw, _x.rpy_dot_dot.roll, _x.rpy_dot_dot.pitch, _x.rpy_dot_dot.yaw, _x.pn_wrt_home.north, _x.pn_wrt_home.east, _x.pn_wrt_home.down, _x.pn_dot.north, _x.pn_dot.east, _x.pn_dot.down, _x.pn_dot_dot.north, _x.pn_dot_dot.east, _x.pn_dot_dot.down, _x.vb.surge, _x.vb.sway, _x.vb.heave, _x.vb_dot.surge, _x.vb_dot.sway, _x.vb_dot.heave, _x.wb.surge, _x.wb.sway, _x.wb.heave, _x.wb_dot.surge, _x.wb_dot.sway, _x.wb_dot.heave, _x.depth_unconstrained, _x.final_reference, _x.lla_final.latitude, _x.lla_final.longitude, _x.lla_final.altitude, _x.rpy_final.roll, _x.rpy_final.pitch, _x.rpy_final.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lla is None:
        self.lla = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.lld is None:
        self.lld = marta_msgs.msg.LatitudeLongitudeDepth()
      if self.quaternion is None:
        self.quaternion = marta_msgs.msg.Quaternion()
      if self.rpy is None:
        self.rpy = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot is None:
        self.rpy_dot = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot_dot is None:
        self.rpy_dot_dot = marta_msgs.msg.RollPitchYaw()
      if self.pn_wrt_home is None:
        self.pn_wrt_home = marta_msgs.msg.NorthEastDown()
      if self.pn_dot is None:
        self.pn_dot = marta_msgs.msg.NorthEastDown()
      if self.pn_dot_dot is None:
        self.pn_dot_dot = marta_msgs.msg.NorthEastDown()
      if self.vb is None:
        self.vb = marta_msgs.msg.SurgeSwayHeave()
      if self.vb_dot is None:
        self.vb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.wb is None:
        self.wb = marta_msgs.msg.SurgeSwayHeave()
      if self.wb_dot is None:
        self.wb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.lla_final is None:
        self.lla_final = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.rpy_final is None:
        self.rpy_final = marta_msgs.msg.RollPitchYaw()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 377
      (_x.lla.latitude, _x.lla.longitude, _x.lla.altitude, _x.lld.latitude, _x.lld.longitude, _x.lld.depth, _x.quaternion.w, _x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.rpy_dot.roll, _x.rpy_dot.pitch, _x.rpy_dot.yaw, _x.rpy_dot_dot.roll, _x.rpy_dot_dot.pitch, _x.rpy_dot_dot.yaw, _x.pn_wrt_home.north, _x.pn_wrt_home.east, _x.pn_wrt_home.down, _x.pn_dot.north, _x.pn_dot.east, _x.pn_dot.down, _x.pn_dot_dot.north, _x.pn_dot_dot.east, _x.pn_dot_dot.down, _x.vb.surge, _x.vb.sway, _x.vb.heave, _x.vb_dot.surge, _x.vb_dot.sway, _x.vb_dot.heave, _x.wb.surge, _x.wb.sway, _x.wb.heave, _x.wb_dot.surge, _x.wb_dot.sway, _x.wb_dot.heave, _x.depth_unconstrained, _x.final_reference, _x.lla_final.latitude, _x.lla_final.longitude, _x.lla_final.altitude, _x.rpy_final.roll, _x.rpy_final.pitch, _x.rpy_final.yaw,) = _get_struct_41dB6d().unpack(str[start:end])
      self.final_reference = bool(self.final_reference)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_41dB6d().pack(_x.lla.latitude, _x.lla.longitude, _x.lla.altitude, _x.lld.latitude, _x.lld.longitude, _x.lld.depth, _x.quaternion.w, _x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.rpy_dot.roll, _x.rpy_dot.pitch, _x.rpy_dot.yaw, _x.rpy_dot_dot.roll, _x.rpy_dot_dot.pitch, _x.rpy_dot_dot.yaw, _x.pn_wrt_home.north, _x.pn_wrt_home.east, _x.pn_wrt_home.down, _x.pn_dot.north, _x.pn_dot.east, _x.pn_dot.down, _x.pn_dot_dot.north, _x.pn_dot_dot.east, _x.pn_dot_dot.down, _x.vb.surge, _x.vb.sway, _x.vb.heave, _x.vb_dot.surge, _x.vb_dot.sway, _x.vb_dot.heave, _x.wb.surge, _x.wb.sway, _x.wb.heave, _x.wb_dot.surge, _x.wb_dot.sway, _x.wb_dot.heave, _x.depth_unconstrained, _x.final_reference, _x.lla_final.latitude, _x.lla_final.longitude, _x.lla_final.altitude, _x.rpy_final.roll, _x.rpy_final.pitch, _x.rpy_final.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lla is None:
        self.lla = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.lld is None:
        self.lld = marta_msgs.msg.LatitudeLongitudeDepth()
      if self.quaternion is None:
        self.quaternion = marta_msgs.msg.Quaternion()
      if self.rpy is None:
        self.rpy = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot is None:
        self.rpy_dot = marta_msgs.msg.RollPitchYaw()
      if self.rpy_dot_dot is None:
        self.rpy_dot_dot = marta_msgs.msg.RollPitchYaw()
      if self.pn_wrt_home is None:
        self.pn_wrt_home = marta_msgs.msg.NorthEastDown()
      if self.pn_dot is None:
        self.pn_dot = marta_msgs.msg.NorthEastDown()
      if self.pn_dot_dot is None:
        self.pn_dot_dot = marta_msgs.msg.NorthEastDown()
      if self.vb is None:
        self.vb = marta_msgs.msg.SurgeSwayHeave()
      if self.vb_dot is None:
        self.vb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.wb is None:
        self.wb = marta_msgs.msg.SurgeSwayHeave()
      if self.wb_dot is None:
        self.wb_dot = marta_msgs.msg.SurgeSwayHeave()
      if self.lla_final is None:
        self.lla_final = marta_msgs.msg.LatitudeLongitudeAltitude()
      if self.rpy_final is None:
        self.rpy_final = marta_msgs.msg.RollPitchYaw()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 377
      (_x.lla.latitude, _x.lla.longitude, _x.lla.altitude, _x.lld.latitude, _x.lld.longitude, _x.lld.depth, _x.quaternion.w, _x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.rpy_dot.roll, _x.rpy_dot.pitch, _x.rpy_dot.yaw, _x.rpy_dot_dot.roll, _x.rpy_dot_dot.pitch, _x.rpy_dot_dot.yaw, _x.pn_wrt_home.north, _x.pn_wrt_home.east, _x.pn_wrt_home.down, _x.pn_dot.north, _x.pn_dot.east, _x.pn_dot.down, _x.pn_dot_dot.north, _x.pn_dot_dot.east, _x.pn_dot_dot.down, _x.vb.surge, _x.vb.sway, _x.vb.heave, _x.vb_dot.surge, _x.vb_dot.sway, _x.vb_dot.heave, _x.wb.surge, _x.wb.sway, _x.wb.heave, _x.wb_dot.surge, _x.wb_dot.sway, _x.wb_dot.heave, _x.depth_unconstrained, _x.final_reference, _x.lla_final.latitude, _x.lla_final.longitude, _x.lla_final.altitude, _x.rpy_final.roll, _x.rpy_final.pitch, _x.rpy_final.yaw,) = _get_struct_41dB6d().unpack(str[start:end])
      self.final_reference = bool(self.final_reference)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_41dB6d = None
def _get_struct_41dB6d():
    global _struct_41dB6d
    if _struct_41dB6d is None:
        _struct_41dB6d = struct.Struct("<41dB6d")
    return _struct_41dB6d
