// Generated by gencpp from file marta_msgs/Distance.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_DISTANCE_H
#define MARTA_MSGS_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marta_msgs
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : header()
    , distance(0.0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::marta_msgs::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::marta_msgs::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::marta_msgs::Distance > DistancePtr;
typedef boost::shared_ptr< ::marta_msgs::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::Distance_<ContainerAllocator1> & lhs, const ::marta_msgs::Distance_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::Distance_<ContainerAllocator1> & lhs, const ::marta_msgs::Distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::Distance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::Distance_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "927a6968211c82bd71bee6aee6c4b1b6";
  }

  static const char* value(const ::marta_msgs::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x927a6968211c82bdULL;
  static const uint64_t static_value2 = 0x71bee6aee6c4b1b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/Distance";
  }

  static const char* value(const ::marta_msgs::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::marta_msgs::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::Distance_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_DISTANCE_H
