// Generated by gencpp from file marta_msgs/LatitudeLongitudeDepth.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_LATITUDELONGITUDEDEPTH_H
#define MARTA_MSGS_MESSAGE_LATITUDELONGITUDEDEPTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marta_msgs
{
template <class ContainerAllocator>
struct LatitudeLongitudeDepth_
{
  typedef LatitudeLongitudeDepth_<ContainerAllocator> Type;

  LatitudeLongitudeDepth_()
    : latitude(0.0)
    , longitude(0.0)
    , depth(0.0)  {
    }
  LatitudeLongitudeDepth_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> const> ConstPtr;

}; // struct LatitudeLongitudeDepth_

typedef ::marta_msgs::LatitudeLongitudeDepth_<std::allocator<void> > LatitudeLongitudeDepth;

typedef boost::shared_ptr< ::marta_msgs::LatitudeLongitudeDepth > LatitudeLongitudeDepthPtr;
typedef boost::shared_ptr< ::marta_msgs::LatitudeLongitudeDepth const> LatitudeLongitudeDepthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator1> & lhs, const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator1> & lhs, const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f7d102e64867310c926f4f670659eba";
  }

  static const char* value(const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f7d102e64867310ULL;
  static const uint64_t static_value2 = 0xc926f4f670659ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/LatitudeLongitudeDepth";
  }

  static const char* value(const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 depth\n"
;
  }

  static const char* value(const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LatitudeLongitudeDepth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_LATITUDELONGITUDEDEPTH_H
