// Generated by gencpp from file marta_msgs/MotionReference.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_MOTIONREFERENCE_H
#define MARTA_MSGS_MESSAGE_MOTIONREFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marta_msgs/LatitudeLongitudeAltitude.h>
#include <marta_msgs/LatitudeLongitudeDepth.h>
#include <marta_msgs/Quaternion.h>
#include <marta_msgs/RollPitchYaw.h>
#include <marta_msgs/RollPitchYaw.h>
#include <marta_msgs/RollPitchYaw.h>
#include <marta_msgs/NorthEastDown.h>
#include <marta_msgs/NorthEastDown.h>
#include <marta_msgs/NorthEastDown.h>
#include <marta_msgs/SurgeSwayHeave.h>
#include <marta_msgs/SurgeSwayHeave.h>
#include <marta_msgs/SurgeSwayHeave.h>
#include <marta_msgs/SurgeSwayHeave.h>
#include <marta_msgs/LatitudeLongitudeAltitude.h>
#include <marta_msgs/RollPitchYaw.h>

namespace marta_msgs
{
template <class ContainerAllocator>
struct MotionReference_
{
  typedef MotionReference_<ContainerAllocator> Type;

  MotionReference_()
    : header()
    , lla()
    , lld()
    , quaternion()
    , rpy()
    , rpy_dot()
    , rpy_dot_dot()
    , pn_wrt_home()
    , pn_dot()
    , pn_dot_dot()
    , vb()
    , vb_dot()
    , wb()
    , wb_dot()
    , depth_unconstrained(0.0)
    , final_reference(false)
    , lla_final()
    , rpy_final()  {
    }
  MotionReference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lla(_alloc)
    , lld(_alloc)
    , quaternion(_alloc)
    , rpy(_alloc)
    , rpy_dot(_alloc)
    , rpy_dot_dot(_alloc)
    , pn_wrt_home(_alloc)
    , pn_dot(_alloc)
    , pn_dot_dot(_alloc)
    , vb(_alloc)
    , vb_dot(_alloc)
    , wb(_alloc)
    , wb_dot(_alloc)
    , depth_unconstrained(0.0)
    , final_reference(false)
    , lla_final(_alloc)
    , rpy_final(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::marta_msgs::LatitudeLongitudeAltitude_<ContainerAllocator>  _lla_type;
  _lla_type lla;

   typedef  ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator>  _lld_type;
  _lld_type lld;

   typedef  ::marta_msgs::Quaternion_<ContainerAllocator>  _quaternion_type;
  _quaternion_type quaternion;

   typedef  ::marta_msgs::RollPitchYaw_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;

   typedef  ::marta_msgs::RollPitchYaw_<ContainerAllocator>  _rpy_dot_type;
  _rpy_dot_type rpy_dot;

   typedef  ::marta_msgs::RollPitchYaw_<ContainerAllocator>  _rpy_dot_dot_type;
  _rpy_dot_dot_type rpy_dot_dot;

   typedef  ::marta_msgs::NorthEastDown_<ContainerAllocator>  _pn_wrt_home_type;
  _pn_wrt_home_type pn_wrt_home;

   typedef  ::marta_msgs::NorthEastDown_<ContainerAllocator>  _pn_dot_type;
  _pn_dot_type pn_dot;

   typedef  ::marta_msgs::NorthEastDown_<ContainerAllocator>  _pn_dot_dot_type;
  _pn_dot_dot_type pn_dot_dot;

   typedef  ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>  _vb_type;
  _vb_type vb;

   typedef  ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>  _vb_dot_type;
  _vb_dot_type vb_dot;

   typedef  ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>  _wb_type;
  _wb_type wb;

   typedef  ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>  _wb_dot_type;
  _wb_dot_type wb_dot;

   typedef double _depth_unconstrained_type;
  _depth_unconstrained_type depth_unconstrained;

   typedef uint8_t _final_reference_type;
  _final_reference_type final_reference;

   typedef  ::marta_msgs::LatitudeLongitudeAltitude_<ContainerAllocator>  _lla_final_type;
  _lla_final_type lla_final;

   typedef  ::marta_msgs::RollPitchYaw_<ContainerAllocator>  _rpy_final_type;
  _rpy_final_type rpy_final;





  typedef boost::shared_ptr< ::marta_msgs::MotionReference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::MotionReference_<ContainerAllocator> const> ConstPtr;

}; // struct MotionReference_

typedef ::marta_msgs::MotionReference_<std::allocator<void> > MotionReference;

typedef boost::shared_ptr< ::marta_msgs::MotionReference > MotionReferencePtr;
typedef boost::shared_ptr< ::marta_msgs::MotionReference const> MotionReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::MotionReference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::MotionReference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::MotionReference_<ContainerAllocator1> & lhs, const ::marta_msgs::MotionReference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lla == rhs.lla &&
    lhs.lld == rhs.lld &&
    lhs.quaternion == rhs.quaternion &&
    lhs.rpy == rhs.rpy &&
    lhs.rpy_dot == rhs.rpy_dot &&
    lhs.rpy_dot_dot == rhs.rpy_dot_dot &&
    lhs.pn_wrt_home == rhs.pn_wrt_home &&
    lhs.pn_dot == rhs.pn_dot &&
    lhs.pn_dot_dot == rhs.pn_dot_dot &&
    lhs.vb == rhs.vb &&
    lhs.vb_dot == rhs.vb_dot &&
    lhs.wb == rhs.wb &&
    lhs.wb_dot == rhs.wb_dot &&
    lhs.depth_unconstrained == rhs.depth_unconstrained &&
    lhs.final_reference == rhs.final_reference &&
    lhs.lla_final == rhs.lla_final &&
    lhs.rpy_final == rhs.rpy_final;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::MotionReference_<ContainerAllocator1> & lhs, const ::marta_msgs::MotionReference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::MotionReference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::MotionReference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::MotionReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::MotionReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::MotionReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::MotionReference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::MotionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6865ee91600578e5e1d5b6edf162a80";
  }

  static const char* value(const ::marta_msgs::MotionReference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6865ee91600578eULL;
  static const uint64_t static_value2 = 0x5e1d5b6edf162a80ULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::MotionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/MotionReference";
  }

  static const char* value(const ::marta_msgs::MotionReference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::MotionReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"LatitudeLongitudeAltitude lla\n"
"\n"
"LatitudeLongitudeDepth lld\n"
"\n"
"Quaternion quaternion\n"
"\n"
"RollPitchYaw rpy\n"
"\n"
"RollPitchYaw rpy_dot\n"
"\n"
"RollPitchYaw rpy_dot_dot\n"
"\n"
"NorthEastDown pn_wrt_home\n"
"\n"
"NorthEastDown pn_dot\n"
"\n"
"NorthEastDown pn_dot_dot\n"
"\n"
"SurgeSwayHeave vb\n"
"\n"
"SurgeSwayHeave vb_dot\n"
"\n"
"SurgeSwayHeave wb\n"
"\n"
"SurgeSwayHeave wb_dot\n"
"\n"
"float64 depth_unconstrained\n"
"	\n"
"bool final_reference\n"
"\n"
"LatitudeLongitudeAltitude lla_final\n"
"\n"
"RollPitchYaw rpy_final\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/LatitudeLongitudeAltitude\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/LatitudeLongitudeDepth\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 depth\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Quaternion\n"
"float64 w\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/RollPitchYaw\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/NorthEastDown\n"
"float64 north\n"
"float64 east\n"
"float64 down\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/SurgeSwayHeave\n"
"float64 surge\n"
"float64 sway\n"
"float64 heave\n"
;
  }

  static const char* value(const ::marta_msgs::MotionReference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::MotionReference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lla);
      stream.next(m.lld);
      stream.next(m.quaternion);
      stream.next(m.rpy);
      stream.next(m.rpy_dot);
      stream.next(m.rpy_dot_dot);
      stream.next(m.pn_wrt_home);
      stream.next(m.pn_dot);
      stream.next(m.pn_dot_dot);
      stream.next(m.vb);
      stream.next(m.vb_dot);
      stream.next(m.wb);
      stream.next(m.wb_dot);
      stream.next(m.depth_unconstrained);
      stream.next(m.final_reference);
      stream.next(m.lla_final);
      stream.next(m.rpy_final);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionReference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::MotionReference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::MotionReference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lla: ";
    s << std::endl;
    Printer< ::marta_msgs::LatitudeLongitudeAltitude_<ContainerAllocator> >::stream(s, indent + "  ", v.lla);
    s << indent << "lld: ";
    s << std::endl;
    Printer< ::marta_msgs::LatitudeLongitudeDepth_<ContainerAllocator> >::stream(s, indent + "  ", v.lld);
    s << indent << "quaternion: ";
    s << std::endl;
    Printer< ::marta_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quaternion);
    s << indent << "rpy: ";
    s << std::endl;
    Printer< ::marta_msgs::RollPitchYaw_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
    s << indent << "rpy_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::RollPitchYaw_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_dot);
    s << indent << "rpy_dot_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::RollPitchYaw_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_dot_dot);
    s << indent << "pn_wrt_home: ";
    s << std::endl;
    Printer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >::stream(s, indent + "  ", v.pn_wrt_home);
    s << indent << "pn_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >::stream(s, indent + "  ", v.pn_dot);
    s << indent << "pn_dot_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >::stream(s, indent + "  ", v.pn_dot_dot);
    s << indent << "vb: ";
    s << std::endl;
    Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >::stream(s, indent + "  ", v.vb);
    s << indent << "vb_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >::stream(s, indent + "  ", v.vb_dot);
    s << indent << "wb: ";
    s << std::endl;
    Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >::stream(s, indent + "  ", v.wb);
    s << indent << "wb_dot: ";
    s << std::endl;
    Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >::stream(s, indent + "  ", v.wb_dot);
    s << indent << "depth_unconstrained: ";
    Printer<double>::stream(s, indent + "  ", v.depth_unconstrained);
    s << indent << "final_reference: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.final_reference);
    s << indent << "lla_final: ";
    s << std::endl;
    Printer< ::marta_msgs::LatitudeLongitudeAltitude_<ContainerAllocator> >::stream(s, indent + "  ", v.lla_final);
    s << indent << "rpy_final: ";
    s << std::endl;
    Printer< ::marta_msgs::RollPitchYaw_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_final);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_MOTIONREFERENCE_H
