// Generated by gencpp from file marta_msgs/NavStatus.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_NAVSTATUS_H
#define MARTA_MSGS_MESSAGE_NAVSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marta_msgs/Position.h>
#include <marta_msgs/Euler.h>
#include <marta_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace marta_msgs
{
template <class ContainerAllocator>
struct NavStatus_
{
  typedef NavStatus_<ContainerAllocator> Type;

  NavStatus_()
    : header()
    , position()
    , orientation()
    , quaternion()
    , ned_speed()
    , omega_body()
    , gps_status(0)
    , initialized(false)  {
    }
  NavStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , orientation(_alloc)
    , quaternion(_alloc)
    , ned_speed(_alloc)
    , omega_body(_alloc)
    , gps_status(0)
    , initialized(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::marta_msgs::Position_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::marta_msgs::Euler_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::marta_msgs::Quaternion_<ContainerAllocator>  _quaternion_type;
  _quaternion_type quaternion;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ned_speed_type;
  _ned_speed_type ned_speed;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _omega_body_type;
  _omega_body_type omega_body;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;

   typedef uint8_t _initialized_type;
  _initialized_type initialized;





  typedef boost::shared_ptr< ::marta_msgs::NavStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::NavStatus_<ContainerAllocator> const> ConstPtr;

}; // struct NavStatus_

typedef ::marta_msgs::NavStatus_<std::allocator<void> > NavStatus;

typedef boost::shared_ptr< ::marta_msgs::NavStatus > NavStatusPtr;
typedef boost::shared_ptr< ::marta_msgs::NavStatus const> NavStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::NavStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::NavStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::NavStatus_<ContainerAllocator1> & lhs, const ::marta_msgs::NavStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.quaternion == rhs.quaternion &&
    lhs.ned_speed == rhs.ned_speed &&
    lhs.omega_body == rhs.omega_body &&
    lhs.gps_status == rhs.gps_status &&
    lhs.initialized == rhs.initialized;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::NavStatus_<ContainerAllocator1> & lhs, const ::marta_msgs::NavStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::NavStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::NavStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::NavStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::NavStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::NavStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::NavStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::NavStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2652576ed189854bff45893603a05bc0";
  }

  static const char* value(const ::marta_msgs::NavStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2652576ed189854bULL;
  static const uint64_t static_value2 = 0xff45893603a05bc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::NavStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/NavStatus";
  }

  static const char* value(const ::marta_msgs::NavStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::NavStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"marta_msgs/Position position\n"
" \n"
"marta_msgs/Euler orientation\n"
"\n"
"marta_msgs/Quaternion quaternion\n"
"\n"
"geometry_msgs/Vector3 ned_speed\n"
"\n"
"geometry_msgs/Vector3 omega_body\n"
"\n"
"uint8 gps_status\n"
"\n"
"bool initialized\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Position\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 depth\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Euler\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Quaternion\n"
"float64 w\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::marta_msgs::NavStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::NavStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.quaternion);
      stream.next(m.ned_speed);
      stream.next(m.omega_body);
      stream.next(m.gps_status);
      stream.next(m.initialized);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::NavStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::NavStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::marta_msgs::Position_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::marta_msgs::Euler_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "quaternion: ";
    s << std::endl;
    Printer< ::marta_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quaternion);
    s << indent << "ned_speed: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ned_speed);
    s << indent << "omega_body: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.omega_body);
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
    s << indent << "initialized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initialized);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_NAVSTATUS_H
