// Generated by gencpp from file marta_msgs/NorthEastDown.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_NORTHEASTDOWN_H
#define MARTA_MSGS_MESSAGE_NORTHEASTDOWN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marta_msgs
{
template <class ContainerAllocator>
struct NorthEastDown_
{
  typedef NorthEastDown_<ContainerAllocator> Type;

  NorthEastDown_()
    : north(0.0)
    , east(0.0)
    , down(0.0)  {
    }
  NorthEastDown_(const ContainerAllocator& _alloc)
    : north(0.0)
    , east(0.0)
    , down(0.0)  {
  (void)_alloc;
    }



   typedef double _north_type;
  _north_type north;

   typedef double _east_type;
  _east_type east;

   typedef double _down_type;
  _down_type down;





  typedef boost::shared_ptr< ::marta_msgs::NorthEastDown_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::NorthEastDown_<ContainerAllocator> const> ConstPtr;

}; // struct NorthEastDown_

typedef ::marta_msgs::NorthEastDown_<std::allocator<void> > NorthEastDown;

typedef boost::shared_ptr< ::marta_msgs::NorthEastDown > NorthEastDownPtr;
typedef boost::shared_ptr< ::marta_msgs::NorthEastDown const> NorthEastDownConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::NorthEastDown_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::NorthEastDown_<ContainerAllocator1> & lhs, const ::marta_msgs::NorthEastDown_<ContainerAllocator2> & rhs)
{
  return lhs.north == rhs.north &&
    lhs.east == rhs.east &&
    lhs.down == rhs.down;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::NorthEastDown_<ContainerAllocator1> & lhs, const ::marta_msgs::NorthEastDown_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::NorthEastDown_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::NorthEastDown_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::NorthEastDown_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81fca827a727a73c11e9d24a75a9174f";
  }

  static const char* value(const ::marta_msgs::NorthEastDown_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81fca827a727a73cULL;
  static const uint64_t static_value2 = 0x11e9d24a75a9174fULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/NorthEastDown";
  }

  static const char* value(const ::marta_msgs::NorthEastDown_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 north\n"
"float64 east\n"
"float64 down\n"
;
  }

  static const char* value(const ::marta_msgs::NorthEastDown_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.north);
      stream.next(m.east);
      stream.next(m.down);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NorthEastDown_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::NorthEastDown_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::NorthEastDown_<ContainerAllocator>& v)
  {
    s << indent << "north: ";
    Printer<double>::stream(s, indent + "  ", v.north);
    s << indent << "east: ";
    Printer<double>::stream(s, indent + "  ", v.east);
    s << indent << "down: ";
    Printer<double>::stream(s, indent + "  ", v.down);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_NORTHEASTDOWN_H
