// Generated by gencpp from file marta_msgs/SideScanSonar.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_SIDESCANSONAR_H
#define MARTA_MSGS_MESSAGE_SIDESCANSONAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt8MultiArray.h>
#include <std_msgs/UInt8MultiArray.h>

namespace marta_msgs
{
template <class ContainerAllocator>
struct SideScanSonar_
{
  typedef SideScanSonar_<ContainerAllocator> Type;

  SideScanSonar_()
    : header()
    , range(0.0)
    , left_beam()
    , right_beam()  {
    }
  SideScanSonar_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range(0.0)
    , left_beam(_alloc)
    , right_beam(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _range_type;
  _range_type range;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _left_beam_type;
  _left_beam_type left_beam;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _right_beam_type;
  _right_beam_type right_beam;





  typedef boost::shared_ptr< ::marta_msgs::SideScanSonar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::SideScanSonar_<ContainerAllocator> const> ConstPtr;

}; // struct SideScanSonar_

typedef ::marta_msgs::SideScanSonar_<std::allocator<void> > SideScanSonar;

typedef boost::shared_ptr< ::marta_msgs::SideScanSonar > SideScanSonarPtr;
typedef boost::shared_ptr< ::marta_msgs::SideScanSonar const> SideScanSonarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::SideScanSonar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::SideScanSonar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::SideScanSonar_<ContainerAllocator1> & lhs, const ::marta_msgs::SideScanSonar_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.range == rhs.range &&
    lhs.left_beam == rhs.left_beam &&
    lhs.right_beam == rhs.right_beam;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::SideScanSonar_<ContainerAllocator1> & lhs, const ::marta_msgs::SideScanSonar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::SideScanSonar_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::SideScanSonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::SideScanSonar_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88e1d1c22f1868590e9f2ba229dda693";
  }

  static const char* value(const ::marta_msgs::SideScanSonar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88e1d1c22f186859ULL;
  static const uint64_t static_value2 = 0x0e9f2ba229dda693ULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/SideScanSonar";
  }

  static const char* value(const ::marta_msgs::SideScanSonar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                     header\n"
"\n"
"float32                    range\n"
"\n"
"std_msgs/UInt8MultiArray   left_beam\n"
"\n"
"std_msgs/UInt8MultiArray   right_beam\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::marta_msgs::SideScanSonar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range);
      stream.next(m.left_beam);
      stream.next(m.right_beam);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SideScanSonar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::SideScanSonar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::SideScanSonar_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "left_beam: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.left_beam);
    s << indent << "right_beam: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.right_beam);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_SIDESCANSONAR_H
