// Generated by gencpp from file marta_msgs/SurgeSwayHeave.msg
// DO NOT EDIT!


#ifndef MARTA_MSGS_MESSAGE_SURGESWAYHEAVE_H
#define MARTA_MSGS_MESSAGE_SURGESWAYHEAVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marta_msgs
{
template <class ContainerAllocator>
struct SurgeSwayHeave_
{
  typedef SurgeSwayHeave_<ContainerAllocator> Type;

  SurgeSwayHeave_()
    : surge(0.0)
    , sway(0.0)
    , heave(0.0)  {
    }
  SurgeSwayHeave_(const ContainerAllocator& _alloc)
    : surge(0.0)
    , sway(0.0)
    , heave(0.0)  {
  (void)_alloc;
    }



   typedef double _surge_type;
  _surge_type surge;

   typedef double _sway_type;
  _sway_type sway;

   typedef double _heave_type;
  _heave_type heave;





  typedef boost::shared_ptr< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> const> ConstPtr;

}; // struct SurgeSwayHeave_

typedef ::marta_msgs::SurgeSwayHeave_<std::allocator<void> > SurgeSwayHeave;

typedef boost::shared_ptr< ::marta_msgs::SurgeSwayHeave > SurgeSwayHeavePtr;
typedef boost::shared_ptr< ::marta_msgs::SurgeSwayHeave const> SurgeSwayHeaveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator1> & lhs, const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator2> & rhs)
{
  return lhs.surge == rhs.surge &&
    lhs.sway == rhs.sway &&
    lhs.heave == rhs.heave;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator1> & lhs, const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37a93273a4b90846c44a065401ed273f";
  }

  static const char* value(const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37a93273a4b90846ULL;
  static const uint64_t static_value2 = 0xc44a065401ed273fULL;
};

template<class ContainerAllocator>
struct DataType< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marta_msgs/SurgeSwayHeave";
  }

  static const char* value(const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 surge\n"
"float64 sway\n"
"float64 heave\n"
;
  }

  static const char* value(const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.surge);
      stream.next(m.sway);
      stream.next(m.heave);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SurgeSwayHeave_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marta_msgs::SurgeSwayHeave_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marta_msgs::SurgeSwayHeave_<ContainerAllocator>& v)
  {
    s << indent << "surge: ";
    Printer<double>::stream(s, indent + "  ", v.surge);
    s << indent << "sway: ";
    Printer<double>::stream(s, indent + "  ", v.sway);
    s << indent << "heave: ";
    Printer<double>::stream(s, indent + "  ", v.heave);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTA_MSGS_MESSAGE_SURGESWAYHEAVE_H
