(cl:in-package marta_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LLA-VAL
          LLA
          LLD-VAL
          LLD
          QUATERNION-VAL
          QUATERNION
          RPY-VAL
          RPY
          RPY_DOT-VAL
          RPY_DOT
          RPY_DOT_DOT-VAL
          RPY_DOT_DOT
          PN_WRT_HOME-VAL
          PN_WRT_HOME
          PN_DOT-VAL
          PN_DOT
          PN_DOT_DOT-VAL
          PN_DOT_DOT
          VB-VAL
          VB
          VB_DOT-VAL
          VB_DOT
          WB-VAL
          WB
          WB_DOT-VAL
          WB_DOT
          DEPTH_UNCONSTRAINED-VAL
          DEPTH_UNCONSTRAINED
          FINAL_REFERENCE-VAL
          FINAL_REFERENCE
          LLA_FINAL-VAL
          LLA_FINAL
          RPY_FINAL-VAL
          RPY_FINAL
))