(cl:defpackage marta_msgs-msg
  (:use )
  (:export
   "<DISTANCE>"
   "DISTANCE"
   "<EULER>"
   "EULER"
   "<LATITUDELONGITUDEALTITUDE>"
   "LATITUDELONGITUDEALTITUDE"
   "<LATITUDELONGITUDEDEPTH>"
   "LATITUDELONGITUDEDEPTH"
   "<MOTIONREFERENCE>"
   "MOTIONREFERENCE"
   "<NAVSTATUS>"
   "NAVSTATUS"
   "<NORTHEASTDOWN>"
   "NORTHEASTDOWN"
   "<POSITION>"
   "POSITION"
   "<QUATERNION>"
   "QUATERNION"
   "<ROLLPITCHYAW>"
   "ROLLPITCHYAW"
   "<SIDESCANSONAR>"
   "SIDESCANSONAR"
   "<SURGESWAYHEAVE>"
   "SURGESWAYHEAVE"
  ))

