// Generated by gencpp from file zeno_python/WaypointPath.msg
// DO NOT EDIT!


#ifndef ZENO_PYTHON_MESSAGE_WAYPOINTPATH_H
#define ZENO_PYTHON_MESSAGE_WAYPOINTPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace zeno_python
{
template <class ContainerAllocator>
struct WaypointPath_
{
  typedef WaypointPath_<ContainerAllocator> Type;

  WaypointPath_()
    : waypoints()  {
    }
  WaypointPath_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::zeno_python::WaypointPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zeno_python::WaypointPath_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointPath_

typedef ::zeno_python::WaypointPath_<std::allocator<void> > WaypointPath;

typedef boost::shared_ptr< ::zeno_python::WaypointPath > WaypointPathPtr;
typedef boost::shared_ptr< ::zeno_python::WaypointPath const> WaypointPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zeno_python::WaypointPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zeno_python::WaypointPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zeno_python::WaypointPath_<ContainerAllocator1> & lhs, const ::zeno_python::WaypointPath_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zeno_python::WaypointPath_<ContainerAllocator1> & lhs, const ::zeno_python::WaypointPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zeno_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zeno_python::WaypointPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zeno_python::WaypointPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zeno_python::WaypointPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zeno_python::WaypointPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zeno_python::WaypointPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zeno_python::WaypointPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zeno_python::WaypointPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0511c019d3d3f0edeb56aaf3709c8aea";
  }

  static const char* value(const ::zeno_python::WaypointPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0511c019d3d3f0edULL;
  static const uint64_t static_value2 = 0xeb56aaf3709c8aeaULL;
};

template<class ContainerAllocator>
struct DataType< ::zeno_python::WaypointPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zeno_python/WaypointPath";
  }

  static const char* value(const ::zeno_python::WaypointPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zeno_python::WaypointPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] waypoints \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::zeno_python::WaypointPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zeno_python::WaypointPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zeno_python::WaypointPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zeno_python::WaypointPath_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZENO_PYTHON_MESSAGE_WAYPOINTPATH_H
